name: Versioning with GitVersion

on:
  push:
    branches:
      - master
      - develop
      - feature/*
      - hotfix/*

permissions:
  contents: write

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install and Run GitVersion
        uses: gittools/actions/gitversion/execute@v0.9

      - name: Output GitVersion Variables
        run: |
          echo "FullSemVer: ${{ steps.gitversion.outputs.fullsemver }}"
          echo "MajorMinorPatch: ${{ steps.gitversion.outputs.majorminorpatch }}"

      - name: Create tag with new version
        run: |
          git tag ${{ steps.gitversion.outputs.fullsemver }}
          git push origin ${{ steps.gitversion.outputs.fullsemver }}
