name: Auto Increment Version Tag

on:
  push:
    branches:
      - main

jobs:
  increment-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get the latest tag
        id: get_latest_tag
        run: echo "latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV

      - name: Increment tag
        id: increment_tag
        run: |
          latest_tag=$(echo ${{ env.latest_tag }} | sed 's/v//')
          IFS='.' read -r -a version_parts <<< "$latest_tag"
          major=${version_parts[0]}
          minor=${version_parts[1]}
          patch=${version_parts[2]}
          new_patch=$((patch+1))
          new_tag="v${major}.${minor}.${new_patch}"
          echo "new_tag=${new_tag}" >> $GITHUB_ENV

      - name: Create new tag
        run: |
          git tag ${{ env.new_tag }}
          git push origin ${{ env.new_tag }}
