name: Versioning with GitVersion

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - hotfix/*

permissions:
  contents: write

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run GitVersion using Docker
        run: |
          docker run --rm -v "$(pwd):/repo" gittools/gitversion:5.6.11 /repo

      - name: Output GitVersion Variables
        run: |
          echo "FullSemVer: $(docker run --rm -v $(pwd):/repo gittools/gitversion:5.6.11 /repo /output json | jq -r .FullSemVer)"

      - name: Create tag with new version
        run: |
          new_version=$(docker run --rm -v $(pwd):/repo gittools/gitversion:5.6.11 /repo /output json | jq -r .FullSemVer)
          git tag $new_version
          git push origin $new_version
