name: Versioning with GitVersion

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - hotfix/*

permissions:
  contents: write

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install GitVersion
        run: |
          dotnet tool install -g GitVersion.Tool
          export PATH="$PATH:~/.dotnet/tools"

      - name: Run GitVersion
        run: |
          gitversion /output json /showvariable FullSemVer

      - name: Create tag with new version
        run: |
          new_version=$(gitversion /output json /showvariable FullSemVer)
          git tag $new_version
          git push origin $new_version
